### ISSUE TITLE
Add country flag

### ISSUE THREAD

**Issue by DJTommek** [DJTommek/better-location#101]
Add country flag (🇨🇿, 🇬🇧, ...) to location. Might be somewhere in address section but can be near coordinates. Should be visible in inline searching.

**Comment by DJTommek** [comment]
![image](https://github.com/DJTommek/better-location/assets/1372298/b46e144d-85c5-4831-96c8-4231400b732c)

**Comment by xmha97** [comment]
Wow, good idea 👍💡
