### ISSUE TITLE
Service balad.ir

### ISSUE THREAD

**Issue by DJTommek** [DJTommek/better-location#115]
## Service home website
https://balad.ir/

## Example link(s) and their coordinates

Example link | Coordinates |  
-|-
https://balad.ir/location?latitude=35.826644&longitude=50.968268&zoom=16.500000 | `35.826644,50.968268`
https://balad.ir/#6.04/29.513/53.574 | `53.574,29.513`
https://balad.ir/p/3j08MFNHbCGvnu?preview=true | `56.2907653,27.1929549` ([from api](https://poi.raah.ir/web/v4/3j08MFNHbCGvnu))

## Example location link
https://balad.ir/location?latitude=35.826644&longitude=50.968268&zoom=16.500000

## Example drive link
N/A

## Description (optional)
N/A

**Comment by xmha97** [comment]
Thanks 🙏
