### ISSUE TITLE
Service Neshan.org

### ISSUE THREAD

**Issue by DJTommek** [DJTommek/better-location#116]
## Service home website
https://neshan.org/maps

## Example link(s) and their coordinates

Example link | Coordinates |  
-|-
https://neshan.org/maps/@35.822524,50.933589,16.5z,0.0p | `35.822524,50.933589`
https://neshan.org/maps/@50.081311,14.419521,12.7z,0.0p | `50.081311,14.419521`

## Example location link
https://neshan.org/maps/@35.822524,50.933589

## Example drive link
N/A

## Description (optional)
N/A

**Comment by xmha97** [comment]
Thanks 🙏
